name: gae
channels:
    - pytorch
    - nvidia
    - conda-forge
dependencies:
    - numpy
    - python=3.10
    - pytorch-cuda
    - torchaudio
    - torchvision
    - pip
    - pip:
        - mitsuba
        - pyexr
        - pyglm